version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
    networks:
      - web     
      
  servicio-analiticas:
    build: ./servicio-analiticas 
    container_name: servicio-analiticas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio-analiticas.rule=Host(`localhost`) && PathPrefix(`/analiticas`)"
      - "traefik.http.routers.servicio-analiticas.entrypoints=web"
   
      - "traefik.http.middlewares.servicio-analiticas-basicauth.basicauth.users=admin:$$2y$$05$$BudbvtdBvEieYeW8PKHoeuRmtFqhsdLEGFGLXaf2zNrDD.v/SuFhK
"
      - "traefik.http.routers.servicio-analiticas.middlewares=servicio-analiticas-basicauth"
      - "traefik.http.services.servicio-analiticas.loadbalancer.server.port=3000"
    networks:
      - web      
  
  servicio-cliente-x1:
    build: ./servicio-cliente-x
    container_name: servicio-cliente-x1
    environment:
      - CLIENT_ID=x1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio-cliente-x1.rule=Host(`localhost`) && PathPrefix(`/servicio/cliente/x1`)"
      - "traefik.http.routers.servicio-cliente-x1.entrypoints=web"
      - "traefik.http.middlewares.servicio-cliente-x1-strip.stripprefix.prefixes=/servicio/cliente/x"
      - "traefik.http.routers.servicio-cliente-x1.middlewares=servicio-cliente-x1-strip"
      - "traefik.http.services.servicio-cliente-x1.loadbalancer.server.port=3000"
    networks:
      - web

  servicio-cliente-x2:
    build: ./servicio-cliente-x
    container_name: servicio-cliente-x2
    environment:
      - CLIENT_ID=x2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.servicio-cliente-x2.rule=Host(`localhost`) && PathPrefix(`/servicio/cliente/x2`)"
      - "traefik.http.routers.servicio-cliente-x2.entrypoints=web"
      - "traefik.http.middlewares.servicio-cliente-x2-strip.stripprefix.prefixes=/servicio/cliente/x2"
      - "traefik.http.routers.servicio-cliente-x2.middlewares=servicio-cliente-x2-strip"
      - "traefik.http.services.servicio-cliente-x2.loadbalancer.server.port=3000"
    networks:
      - web
networks:
  web:
    driver: bridge
